name: jsonapi_client
version: 0.2.1
environment:
  sdk: '>=1.13.0 <2.0.0'
description: >
  Qurami JSON API Client
authors:
  - Bruno Bellissimo <bruno.bellissimo@qurami.com>
  - Cosmin Alexandru Dobre <alex.dobre@qurami.com>
  - Gianfranco Reppucci <gianfranco.reppucci@qurami.com>
homepage: https://github.com/qurami/jsonapi_client_dart
dependencies:
  http: "^0.11.3+7"
  json_annotation: ^0.2.9
dev_dependencies:
  test: "^0.12.13+4"
  build_runner:
  json_serializable: ^0.5.8
